#!/bin/bash

trap "echo 'Somethign went wrong. Aborting...'; exit" ERR

if [[ -n $(git status --porcelain 2>/dev/null) ]]; then
  echo "Repository is not clean"
  exit 1;
fi

if [[ $(git rev-parse --abbrev-ref HEAD) != "develop" ]]; then
  echo "You're not on develop"
  exit 1;
fi

npm run build
git add -A
git commit -m "Update github.io with built files"
git checkout master
git merge develop
git push origin master
git checkout develop
